### PR TITLE
feat: 🍱 use new SVG logo

### PR DESCRIPTION
**Pull request by nstringham**
This PR updates existing logos but also adds high-resolution logos to be used if the user adds a shortcut to the kendo website to their home screen.

### CODE REVIEW

**Comment by nstringham** [comment]
Before and after on Android
Screenshot_20241006-183836

**Comment by nstringham** [comment]
Before and after on Windows
image

**Comment by nstringham** [comment]
Before and after on iOS
IMG_0406

**Comment by nstringham** [comment]
Before and after on Samsung
Screenshot_20241006_190835_One UI Home

**Review by zalhabash — APPROVED** [review]

**Pull request merged**
