### PR TITLE
Add more spacing on the sides of the content at larger screen sizes

### LINKED ISSUE #43: add padding to the sides of pages to make the site feel more spacious

### PR DESCRIPTION
**Pull request by zalhabash**
Make viewport dynamic at large (1024px) and extra large (1280px) [Pico CSS breakpoints](https://picocss.com/docs/container) using [SASS](https://picocss.com/docs/sass#:~:text=//%20Breakpoints%2C%20viewports%20and%20root%20font%20size)

Closes #43

### CODE REVIEW

**Comment by nstringham** [comment]
I don't think this solves the issue of long lines of text being difficult to read, does it?

**Comment by zalhabash** [comment]
Can we resolve long lines of textby separating out the big paragraphs into smaller ones?

**Comment by zalhabash** [comment]
Oops pressed the wrong button

**Comment by nstringham** [comment]
> Can we resolve long lines of text by separating out the big paragraphs into smaller ones?

I don't understand how paragraph length will effect line length unless you intend to make all paragraphs less than one line of text

**Comment by zalhabash** [comment]
Ok I'm lost. I don't understand what you mean by line length or how to fix it?

**Comment by nstringham** [comment]
Here is an article that explains line length and some of the considerations when choosing how long to make lines of text.
https://en.m.wikipedia.org/wiki/Line_length

**Review by nstringham — APPROVED** [review]

**Pull request merged**
